export const agents = [
  {
    id: "agent-1",
    name: "Omar Sales",
    role: "Sales Agent",
    availability: "Online",
    conversations: 18,
    responseTime: "1m 42s",
  },
  {
    id: "agent-2",
    name: "Lina Supervisor",
    role: "Supervisor",
    availability: "Busy",
    conversations: 34,
    responseTime: "2m 08s",
  },
  {
    id: "agent-3",
    name: "Nadia Admin",
    role: "Admin",
    availability: "Away",
    conversations: 9,
    responseTime: "3m 15s",
  },
];

export const contacts = [
  {
    id: "demo-contact-1",
    name: "Maya Hassan",
    phone: "+20 100 123 4567",
    email: "maya@example.com",
    channel: "whatsapp",
    tags: ["hot-lead", "pricing"],
    status: "active",
    assignedAgent: "Omar Sales",
    botpressUserId: "demo-bp-user-1",
    botpressConvId: "demo-bp-conv-1",
    whatsappOptIn: true,
    lastMessage: "Both. Please connect me with a sales specialist.",
    unreadCount: 2,
    mode: "human",
  },
  {
    id: "demo-contact-2",
    name: "Youssef Adel",
    phone: "+20 111 987 6543",
    email: "youssef@example.com",
    channel: "web",
    tags: ["trial", "enterprise"],
    status: "pending",
    assignedAgent: "Lina Supervisor",
    botpressUserId: "demo-bp-user-2",
    botpressConvId: "demo-bp-conv-2",
    whatsappOptIn: true,
    lastMessage: "Can your bot qualify leads by region?",
    unreadCount: 0,
    mode: "bot",
  },
  {
    id: "demo-contact-3",
    name: "Sara Nabil",
    phone: "+20 122 555 0144",
    email: "sara@example.com",
    channel: "telegram",
    tags: ["renewal"],
    status: "active",
    assignedAgent: "Omar Sales",
    botpressUserId: "demo-bp-user-3",
    botpressConvId: "demo-bp-conv-3",
    whatsappOptIn: false,
    lastMessage: "Thanks, send the invoice to finance.",
    unreadCount: 0,
    mode: "bot",
  },
];

export const messages = [
  {
    id: "m1",
    sender: "customer",
    body: "Hi, I want to compare the sales automation plans.",
    time: "09:14",
  },
  {
    id: "m2",
    sender: "bot",
    body: "I can help with that. Are you looking for WhatsApp, web chat, or both?",
    time: "09:14",
  },
  {
    id: "m3",
    sender: "customer",
    body: "Both. Please connect me with a sales specialist.",
    time: "09:15",
  },
  {
    id: "m4",
    sender: "note",
    body: "Bot detected pricing intent and requested human handoff.",
    time: "09:15",
  },
];

export const campaigns = [
  {
    id: "camp-1",
    name: "Spring reactivation",
    type: "Blast",
    status: "Draft",
    target: "pricing, renewal",
    sent: 0,
    delivered: 0,
    replied: 0,
    converted: 0,
  },
  {
    id: "camp-2",
    name: "Trial onboarding drip",
    type: "Drip",
    status: "Running",
    target: "trial",
    sent: 420,
    delivered: 392,
    replied: 81,
    converted: 24,
  },
  {
    id: "camp-3",
    name: "Enterprise webinar",
    type: "Blast",
    status: "Completed",
    target: "enterprise",
    sent: 1200,
    delivered: 1141,
    replied: 217,
    converted: 63,
  },
];

export const hourlyHeatmap = [
  8, 13, 21, 34, 42, 38, 29, 24, 31, 48, 52, 36,
];
